CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER (
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_EMAIL VARCHAR2(255) NOT NULL UNIQUE,
	MEMBER_PASSWORD VARCHAR2(255),
	MEMBER_ADDRESS VARCHAR2(255),
	MEMBER_RECOMMENDER_EMAIL VARCHAR2(255)
);

SELECT * FROM TBL_MEMBER;

UPDATE TBL_MEMBER
SET MEMBER_RECOMMENDER_EMAIL = 'hong1234@gmail.com'
WHERE ID = 5;

UPDATE TBL_MEMBER
SET MEMBER_RECOMMENDER_EMAIL = 'hong1234@gmail.com'
WHERE ID = 13;

UPDATE TBL_MEMBER
SET MEMBER_RECOMMENDER_EMAIL = 'kim7897@gmail.com'
WHERE ID = 4;

SELECT ID, MEMBER_EMAIL, MEMBER_PASSWORD, MEMBER_ADDRESS, MEMBER_RECOMMENDER_EMAIL
FROM TBL_MEMBER
WHERE MEMBER_EMAIL = (
	SELECT MEMBER_RECOMMENDER_EMAIL
	FROM TBL_MEMBER
	WHERE ID = 5
);