CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_EMAIL VARCHAR2(255) UNIQUE NOT NULL,
	MEMBER_PASSWORD VARCHAR2(255),
	MEMBER_NAME VARCHAR(255) NOT NULL
);

CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) UNIQUE NOT NULL,
	PRODUCT_PRICE NUMBER DEFAULT 0,
	PRODUCT_STOCK NUMBER DEFAULT 999
);

CREATE SEQUENCE SEQ_ORDER;
CREATE TABLE TBL_ORDER (
	ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
	ORDER_COMMENT VARCHAR2(255),
	ORDER_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MEMBER_ID NUMBER,
	PRODUCT_ID NUMBER,
	CONSTRAINT FK_ORDER_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_ORDER_PRODUCT FOREIGN KEY(PRODUCT_ID)
	REFERENCES TBL_PRODUCT(ID)
);

--게시글(TBL_POST)
--- 게시글 제목, 게시글 내용, 게시글 작성 시간
--
--멤버(TBL_MEMBER)
--테이블을 ERD에 설계하고, 
--테이블 간의 관계를 생각하여 관계를 맺은 후 DDL하시오..

CREATE SEQUENCE SEQ_POST;
CREATE TABLE TBL_POST (
	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
	POST_TITLE VARCHAR2(255) NOT NULL,
	POST_CONTENT VARCHAR(255) NOT NULL,
	POST_UPLOAD_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MEMBER_ID NUMBER,
	CONSTRAINT FK_POST_MEMBER FOREIGN KEY (MEMBER_ID)
	REFERENCES TBL_MEMBER(ID)
);

CREATE SEQUENCE SEQ_REPLY;
CREATE TABLE TBL_REPLY (
	ID NUMBER CONSTRAINT PK_REPLY PRIMARY KEY,
	REPLY_CONTENT VARCHAR2(255) NOT NULL,
	REPLY_WRITE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	POST_ID NUMBER,
	MEMBER_ID NUMBER,
	CONSTRAINT FK_REPLY_POST FOREIGN KEY (POST_ID)
	REFERENCES TBL_POST(ID),
	CONSTRAINT FK_REPLY_MEMBER FOREIGN KEY (MEMBER_ID)
	REFERENCES TBL_MEMBER(ID)
);

ALTER TABLE TBL_REPLY MODIFY REPLY_CONTENT NOT NULL;

/*
   요구사항
   유치원을 하려고 하는데, 아이들이 체험학습 프로그램을 신청해야 합니다.
   아이들 정보는 이름, 나이, 성별이 필요하고 학부모는 이름, 나이, 주소, 전화번호, 성별이 필요해요
   체험학습은 체험학습 제목, 체험학습 내용, 이벤트 이미지 여러 장이 필요합니다.
   아이들은 여러 번 체험학습에 등록할 수 있어요.
*/

CREATE SEQUENCE SEQ_CHILDREN;
CREATE TABLE TBL_CHILDREN (
	ID NUMBER CONSTRAINT PK_CHILDREN PRIMARY KEY,
	CHILDREN_NAME VARCHAR2(255) NOT NULL,
	CHILDREN_AGE NUMBER NOT NULL,
	CHILDREN_GENDER CHAR(5) NOT NULL
);

CREATE SEQUENCE SEQ_PARENT;
CREATE TABLE TBL_PARENT (
	ID NUMBER CONSTRAINT PK_PARENT PRIMARY KEY,
	PARENT_NAME VARCHAR2(255) NOT NULL,
	PARENT_AGE NUMBER NOT NULL,
	PARENT_ADDRESS VARCHAR2(255) NOT NULL,
	PARENT_GENDER CHAR(5) NOT NULL
);

CREATE SEQUENCE SEQ_EVENT;
CREATE TABLE TBL_EVENT(
	ID NUMBER CONSTRAINT TBL_EVENT PRIMARY KEY,
	REGISTER_TITLE VARCHAR2(255) NOT NULL,
	REGISTER_CONTENT VARCHAR2(255) NOT NULL
--	REGISTER_EVENT_IMG VARCHAR2(255),
);

CREATE SEQUENCE SEQ_EVENT_IMAGE;
CREATE TABLE TBL_EVENT_IMAGE(
	ID NUMBER CONSTRAINT PK_REGISTER_IMAGE PRIMARY KEY,
	REGISTER_IMAGE_PATH VARCHAR(255),
	EVENT_ID NUMBER,
	CONSTRAINT FK_EVENT_IMAGE_EVENT FOREIGN KEY (EVENT_ID)
	REFERENCES TBL_EVENT(ID)
);

-- 작업중
CREATE TABLE REGISTER(
	ID NUMBER CONSTRAINT PK_REGISTER PRIMARY KEY,
	EVENT_ID NUMBER,
	CHILDREN_ID NUMBER
);

-- 강사님 코드
-- TBL_CHILD
-- 이름, 나이, 성별
--CREATE SEQUENCE SEQ_CHILD;
--CREATE TABLE TBL_CHILD(
--   ID NUMBER CONSTRAINT PK_CHILD PRIMARY KEY,
--   CHILD_NAME VARCHAR2(255) NOT NULL,
--   CHILD_AGE NUMBER,
--   CHILD_GENDER CHAR(5)
--);
--
---- TBL_PARENT
---- 이름, 나이, 주소, 전화번호, 성별
--CREATE SEQUENCE SEQ_PARENT;
--CREATE TABLE TBL_PARENT(
--   ID NUMBER CONSTRAINT PK_PARENT PRIMARY KEY,
--   PARENT_NAME VARCHAR2(255) NOT NULL,
--   PARENT_AGE NUMBER,
--   PARENT_ADDRESS VARCHAR2(255),
--   PARENT_PHONE VARCHAR2(255),
--   PARENT_GENDER CHAR(5),
--   CHILD_ID NUMBER,
--   CONSTRAINT FK_PARENT_CHILD FOREIGN KEY(CHILD_ID)
--   REFERENCES TBL_CHILD(ID)
--);
--
--
---- TBL_FIELD_TRIP
---- 체험학습 제목, 체험학습 내용,
--CREATE SEQUENCE SEQ_FIELD_TRIP;
--CREATE TABLE TBL_FIELD_TRIP(
--   ID NUMBER CONSTRAINT PK_FIELD_TRIP PRIMARY KEY,
--   FIELD_TRIP_NAME VARCHAR2(255) NOT NULL,
--   FIELD_TRIP_CONTENT VARCHAR(255) NOT NULL
--);
--
---- TBL_FIELD_TRIP_IMAGE
--CREATE SEQUENCE SEQ_FIELD_TRIP_IMAGE;
--CREATE TABLE TBL_FIELD_TRIP_IMAGE(
--   ID NUMBER CONSTRAINT PK_FIELD_TRIP_IMAGE PRIMARY KEY,
--   FIELD_TRIP_IMAGE_PATH VARCHAR2(255),
--   FIELD_TRIP_IMAGE_NAME VARCHAR2(255),
--   FIELD_TRIP_ID NUMBER,
--   CONSTRAINT FK_FIELD_TRIP_IMAGE_FIELD_TRIP FOREIGN KEY(FIELD_TRIP_ID)
--   REFERENCES TBL_FIELD_TRIP(ID)
--);
--
---- 신청
--CREATE SEQUENCE SEQ_APPLY;
--CREATE TABLE TBL_APPLY(
--   ID NUMBER CONSTRAINT PK_APPLY PRIMARY KEY,
--   CHILD_ID NUMBER,
--   FIELD_TRIP_ID NUMBER,
--   CONSTRAINT FK_APPLY_CHILD FOREIGN KEY(CHILD_ID)
--   REFERENCES TBL_CHILD(ID),
--   CONSTRAINT FK_APPLY_FIELD_TRIP FOREIGN KEY(FIELD_TRIP_ID)
--   REFERENCES TBL_FIELD_TRIP(ID)
--);

/*
   요구사항
   안녕하세요, 광고 회사를 운영하려고 준비중인 사업가입니다.
   광고주는 기업이고 기업 정보는 이름, 주소, 대표번호, 기업종류(스타트업, 중소기업, 중견기업, 대기업)입니다.
   광고는 제목, 내용이 있고 기업은 여러 광고를 신청할 수 있습니다.
   기업이 광고를 선택할 때에는 카테고리로 선택하며, 대카테고리, 중카테고리, 소카테고리가 있습니다.
*/

--기업종류(스타트업...)
CREATE SEQUENCE SEQ_COMPANY_TYPE;
CREATE TABLE TBL_COMPANY_TYPE (
	ID NUMBER CONSTRAINT PK_COMPANY_TYPE PRIMARY KEY,
	COMPANY_TYPE_TYPE VARCHAR2(255)
);

--기업
CREATE SEQUENCE SEQ_COMPANY; 
CREATE TABLE TBL_COMPANY (
	ID NUMBER CONSTRAINT PK_COMPANY PRIMARY KEY,
	COMPANY_NAME VARCHAR2(255) NOT NULL,
	COMPANY_ADDRESS VARCHAR2(255),
	COMPANY_PHONE_NUMBER VARCHAR2(255),
	COMPANY_TYPE_ID NUMBER,
	CONSTRAINT FK_COMPANY_COMPANY_TYPE FOREIGN KEY (COMPANY_TYPE_ID)
	REFERENCES TBL_COMPANY_TYPE(ID)
);

--카테고리(대카테고리...)
CREATE SEQUENCE SEQ_CATEGORY;
CREATE TABLE TBL_CATEGORY (
	ID NUMBER CONSTRAINT PK_CATEGORY PRIMARY KEY,
	CATEGORY_TYPE VARCHAR2(255)
);

--광고
CREATE SEQUENCE SEQ_AD;
CREATE TABLE TBL_AD (
	ID NUMBER CONSTRAINT PK_AD PRIMARY KEY,
	AD_TITLE VARCHAR2(255) NOT NULL,
	AD_CONTENT VARCHAR2(255) NOT NULL
);

--광고 등록
CREATE SEQUENCE SEQ_APPLY_AD;
CREATE TABLE TBL_APPLY_AD (
	ID NUMBER CONSTRAINT PK_APPLY_AD PRIMARY KEY,
	CATEGORY_ID NUMBER,
	AD_ID NUMBER,
	COMPANY_ID NUMBER,
	CONSTRAINT FK_APPLY_AD_CATEGORY FOREIGN KEY (CATEGORY_ID)
	REFERENCES TBL_CATEGORY(ID),
	CONSTRAINT FK_APPLY_AD_AD FOREIGN KEY (AD_ID)
	REFERENCES TBL_AD(ID),
	CONSTRAINT FK_APPLY_AD_COMPANY FOREIGN KEY (COMPANY_ID)
	REFERENCES TBL_COMPANY(ID)
);

-- 강사님 코드
/*

   요구사항
   안녕하세요, 광고 회사를 운영하려고 준비중인 사업가입니다.
   광고주는 기업이고 기업 정보는 이름, 주소, 대표번호, 기업종류(스타트업, 중소기업, 중견기업, 대기업)입니다.
   광고는 제목, 내용이 있고 기업은 여러 광고를 신청할 수 있습니다.
   기업이 광고를 선택할 때에는 카테고리로 선택하며, 대카테고리, 중카테고리, 소카테고리가 있습니다.

*/

-- 회사
--CREATE SEQUENCE SEQ_COMPANY;
---- 이름, 주소, 대표번호, 기업종류
--CREATE TABLE TBL_COMPANY(
--   ID NUMBER CONSTRAINT PK_COMPANY PRIMARY KEY,
--   COMPANY_NAME VARCHAR2(255) NOT NULL UNIQUE,
--   COMPANY_ADDRESS VARCHAR2(255) NOT NULL,
--   COMPANY_PHONE VARCHAR2(255),
--   COMPNAY_TYPE VARCHAR2(255) NOT NULL,
--   CONSTRAINT COMPNAY_BAN_TYPE CHECK(COMPNAY_TYPE IN ('스타트업', '중소기업', '중견기업', '대기업'))
--);
--
---- 광고
---- 제목, 내용
--CREATE SEQUENCE SEQ_AD;
--CREATE TABLE TBL_AD(
--   ID NUMBER CONSTRAINT PK_AD PRIMARY KEY,
--   AD_TITLE VARCHAR2(255) NOT NULL,
--   AD_CONTENT VARCHAR2(255) NOT NULL
--);
--
---- 신청
--CREATE SEQUENCE SEQ_AD_APPLY;
--CREATE TABLE TBL_AD_APPLY(
--   ID NUMBER CONSTRAINT PK_AD_APPLY PRIMARY KEY,
--   COMPANY_ID NUMBER,
--   AD_ID NUMBER,
--   CONSTRAINT FK_AD_APPLY_COMPANY FOREIGN KEY(COMPANY_ID)
--   REFERENCES TBL_COMPANY(ID),
--   CONSTRAINT FK_AD_APPLY_AD FOREIGN KEY(AD_ID)
--   REFERENCES TBL_AD(ID)
--);
--
--
---- 대카테고리(A)
--CREATE SEQUENCE SEQ_CATEGORY_A;
--CREATE TABLE TBL_CATEGORY_A(
--   ID NUMBER CONSTRAINT PK_CATEGORY_A PRIMARY KEY,
--   CATEGORY_A_NAME VARCHAR2(255) NOT NULL,
--   AD_ID NUMBER,
--   CONSTRAINT FK_CATEGORY_A_AD FOREIGN KEY(AD_ID)
--   REFERENCES TBL_AD(ID)
--);
--
---- 중카테고리(B)
--CREATE SEQUENCE SEQ_CATEGORY_B;
--CREATE TABLE TBL_CATEGORY_B(
--   ID NUMBER CONSTRAINT PK_CATEGORY_B PRIMARY KEY,
--   CATEGORY_B_NAME VARCHAR2(255) NOT NULL,
--   CATEGORY_A_ID NUMBER,
--   CONSTRAINT FK_CATEGORY_B_CATEGORY_A FOREIGN KEY(CATEGORY_A_ID)
--   REFERENCES TBL_CATEGORY_A(ID)
--);
--
---- 소카테고리(C)
--CREATE SEQUENCE SEQ_CATEGORY_C;
--CREATE TABLE TBL_CATEGORY_C(
--   ID NUMBER CONSTRAINT PK_CATEGORY_C PRIMARY KEY,
--   CATEGORY_C_NAME VARCHAR2(255) NOT NULL,
--   CATEGORY_B_ID NUMBER,
--   CONSTRAINT FK_CATEGORY_C_CATEGORY_B FOREIGN KEY(CATEGORY_B_ID)
--   REFERENCES TBL_CATEGORY_B(ID)
--);

