CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) NOT NULL,
	PRODUCT_PRICE NUMBER DEFAULT 0,
	PRODUCT_STOCK NUMBER DEFAULT 999
);

SELECT * FROM TBL_PRODUCT;

SELECT ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_STOCK
FROM TBL_PRODUCT
ORDER BY ID DESC;

INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '노트북', 500000, 20);

SELECT ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_STOCK
FROM TBL_PRODUCT
WHERE ID = 3;

UPDATE TBL_PRODUCT
SET PRODUCT_NAME = '키보드', PRODUCT_PRICE = 50000, PRODUCT_STOCK = 5
WHERE ID = 1;

-- POST
CREATE SEQUENCE SEQ_POST;
CREATE TABLE TBL_POST (
	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
	POST_TITLE VARCHAR2(255) NOT NULL,
	POST_CONTENT VARCHAR2(255) NOT NULL,
	POST_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM TBL_POST;
SELECT ID, POST_TITLE, POST_CONTENT, POST_CREATE_AT
FROM TBL_POST; 

INSERT INTO TBL_POST
VALUES(SEQ_POST.NEXTVAL, 'DANON', '테스트', CURRENT_TIMESTAMP);

SELECT ID, POST_TITLE, POST_CONTENT, POST_CREATE_AT
FROM TBL_POST
WHERE ID = 1;

UPDATE TBL_POST
SET POST_TITLE = '타이틀 수정', POST_CONTENT = '컨텐트 수정', POST_CREATE_AT = CURRENT_TIMESTAMP
WHERE ID = 1;

DELETE FROM TBL_POST
WHERE ID = 24;

-- 전체 목록
--SELECT ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_STOCK
--FROM TBL_PRODUCT
--ORDER BY ID ASC
--
--
--UPDATE TBL_PRODUCT
--SET PRODUCT_NAME = '써니의 쟁반', PRODUCT_PRICE = '50000', PRODUCT_STOCK = 20
--WHERE ID = 24;
--
--
--DELETE FROM TBL_PRODUCT
--WHERE ID = 26;
