-- POST
--CREATE SEQUENCE SEQ_POST;
--CREATE TABLE TBL_POST (
--	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
--	POST_TITLE VARCHAR2(255) NOT NULL,
--	POST_CONTENT VARCHAR2(255) NOT NULL,
--	POST_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
--);
--
--SELECT * FROM TBL_POST;
--SELECT ID, POST_TITLE, POST_CONTENT, POST_CREATE_AT
--FROM TBL_POST; 
--
--
--INSERT INTO TBL_POST
--VALUES(SEQ_POST.NEXTVAL, 'DANON', '테스트', CURRENT_TIMESTAMP);
--
--SELECT ID, POST_TITLE, POST_CONTENT, POST_CREATE_AT
--FROM TBL_POST
--WHERE ID = 1;
--
--UPDATE TBL_POST
--SET POST_TITLE = '타이틀 수정', POST_CONTENT = '컨텐트 수정', POST_CREATE_AT = CURRENT_TIMESTAMP
--WHERE ID = 1;
--
--DELETE FROM TBL_POST
--WHERE ID = 8;

CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) NOT NULL,
	PRODUCT_PRICE NUMBER DEFAULT 0,
	PRODUCT_STOCK NUMBER DEFAULT 999
);

SELECT * FROM TBL_PRODUCT;

-- 멤버 테이블
CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_EMAIL VARCHAR2(255) NOT NULL UNIQUE,
	MEMBER_PASSWORD VARCHAR2(255) NOT NULL,
	MEMBER_NAME VARCHAR2(255) NOT NULL
);

-- 주문 테이블
CREATE SEQUENCE SEQ_ORDER;
CREATE TABLE TBL_ORDER(
	ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
	ORDER_COUNT NUMBER DEFAULT 1,
	PRODUCT_ID NUMBER,
	MEMBER_ID NUMBER,
	CONSTRAINT FK_ORDER_PRODUCT FOREIGN KEY(PRODUCT_ID)
	REFERENCES TBL_PRODUCT(ID),
	CONSTRAINT FK_ORDER_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID)
);

INSERT INTO TBL_MEMBER
VALUES(SEQ_MEMBER.NEXTVAL, 'test123@gmail.com', 'test123!@#', '홍길동');

SELECT * FROM TBL_MEMBER;

SELECT ID, MEMBER_EMAIL, MEMBER_PASSWORD, MEMBER_NAME
FROM TBL_MEMBER
WHERE MEMBER_EMAIL = 'test123@gmail.com'
	AND MEMBER_PASSWORD = 'test123!@#';

SELECT COUNT(*) IS_EXISTS
FROM TBL_MEMBER
WHERE MEMBER_EMAIL = 'test123@gmail.com';

SELECT ID, MEMBER_EMAIL, MEMBER_PASSWORD, MEMBER_NAME
FROM TBL_MEMBER
WHERE MEMBER_EMAIL = 'test123@gmail.com';

--상품
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, 'ura', 10000000, 20);

SELECT ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_STOCK
FROM TBL_PRODUCT
ORDER BY ID DESC;

SELECT * FROM TBL_PRODUCT;

UPDATE TBL_PRODUCT
SET PRODUCT_NAME = '노트북', PRODUCT_PRICE = 10000000, PRODUCT_STOCK = 20
WHERE ID = 1;

DELETE FROM TBL_PRODUCT
WHERE ID = 4;

