CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) NOT NULL,
	PRODUCT_PRICE NUMBER DEFAULT 0,
	PRODUCT_STOCK NUMBER DEFAULT 999
);

SELECT * FROM TBL_PRODUCT;

SELECT ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_STOCK
FROM TBL_PRODUCT
ORDER BY ID DESC;

INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '노트북', 500000, 20);

SELECT ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_STOCK
FROM TBL_PRODUCT
WHERE ID = 3;

-- 전체 목록
--SELECT ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_STOCK
--FROM TBL_PRODUCT
--ORDER BY ID ASC
--
--
--UPDATE TBL_PRODUCT
--SET PRODUCT_NAME = '써니의 쟁반', PRODUCT_PRICE = '50000', PRODUCT_STOCK = 20
--WHERE ID = 24;
--
--
--DELETE FROM TBL_PRODUCT
--WHERE ID = 26;
